# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CBIR.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1284, 828)
        MainWindow.setStyleSheet("background-color: rgb(33, 37, 41);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # --------------------Widget for buttons and image-------------------
        self.widget = QtWidgets.QLabel(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 50, 891, 351))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-color: rgb(52, 58, 64);")
        self.widget.setObjectName("widget")

        #-----------------Upload buttons--------------------------

        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(230, 140, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: transparent;\n"
"color: rgb(233, 236, 239);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icon/cloud_upload_white_192x192.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.getImage)


        #-----------------button new video-----------------------
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 140, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: transparent;\n"
"color: rgb(233, 236, 239);")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")


        #------------------/---------------
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(430, 150, 16, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(233, 236, 239);")
        self.label_6.setObjectName("label_6")


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 400, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(233, 236, 239);")
        self.label_2.setObjectName("label_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(20, 440, 1241, 341))
        self.widget_2.setStyleSheet("background-color: rgb(52, 58, 64);")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(920, 40, 331, 341))
        self.widget_3.setObjectName("widget_3")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(0, 0, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(233, 236, 239);")
        self.label.setObjectName("label")
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_3.setGeometry(QtCore.QRect(50, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("color: rgb(233, 236, 239);")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton.setGeometry(QtCore.QRect(50, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color: rgb(233, 236, 239);")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 90, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color: rgb(233, 236, 239);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(233, 236, 239);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(30, 240, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(233, 236, 239);")
        self.label_5.setObjectName("label_5")
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_4.setGeometry(QtCore.QRect(50, 280, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("color: rgb(233, 236, 239);")
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 0, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(233, 236, 239);")
        self.label_3.setObjectName("label_3")

        #---------------------new-----------
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 27, 61, 21))
        self.pushButton_2.setStyleSheet("color: rgb(233, 236, 239);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.New)
        self.pushButton_2.hide()


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1284, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CBIR/CBVR"))
        self.pushButton.setText(_translate("MainWindow", "Upload Photo"))
        self.pushButton_3.setText(_translate("MainWindow", "Upload Video"))
        self.label_6.setText(_translate("MainWindow", "/"))
        self.label_2.setText(_translate("MainWindow", "Images Retrieved"))
        self.label.setText(_translate("MainWindow", "Choose Search Method:"))
        self.radioButton_3.setText(_translate("MainWindow", "Mean RGB"))
        self.radioButton.setText(_translate("MainWindow", "Histogram"))
        self.radioButton_2.setText(_translate("MainWindow", "Color Layout"))
        self.label_4.setText(_translate("MainWindow", "Image:"))
        self.label_5.setText(_translate("MainWindow", "Video:"))
        self.radioButton_4.setText(_translate("MainWindow", "Histogram"))
        self.label_3.setText(_translate("MainWindow", "Content Based Image/Video Retrivel"))
        self.pushButton_2.setText(_translate("MainWindow", "New"))


    def getImage(self):
        global imagepath
        fname = QFileDialog.getOpenFileName()
        imagepath = fname[0]
        pixmap = QPixmap(imagepath)
        print(imagepath)
        self.pushButton.hide()
        self.label_6.hide()
        self.pushButton_3.hide()
        self.widget.setAlignment(QtCore.Qt.AlignCenter)
        self.widget.setPixmap(pixmap)
        self.pushButton_2.show()

    def New(self):
        self.widget.clear()
        self.pushButton.show()
        self.label_6.show()
        self.pushButton_3.show()
        self.pushButton_2.hide()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
